#!/usr/bin/env bash
set -Eeu
set -o posix
set -o pipefail

declare -r actinium_ng_log="/vagrant/guest_logs/Actinium-ng.log"

declare -r exe_name="$0"
echo_log() {
    local log_target="$actinium_ng_log"
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $exe_name: $@" >> $log_target
}

function error {
    echo "$1" 1>&2
    exit 1
}

echo_log "stopping Actiniumd"
Actiniumd-cli stop
